// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package ru.siksmfp.serialization.harness.model.proto;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>bytes signature = 3;</code>
     */
    com.google.protobuf.ByteString getSignature();

    /**
     * <code>repeated .Address addresses = 4;</code>
     */
    java.util.List<ru.siksmfp.serialization.harness.model.proto.UserProto.Address> 
        getAddressesList();
    /**
     * <code>repeated .Address addresses = 4;</code>
     */
    ru.siksmfp.serialization.harness.model.proto.UserProto.Address getAddresses(int index);
    /**
     * <code>repeated .Address addresses = 4;</code>
     */
    int getAddressesCount();
    /**
     * <code>repeated .Address addresses = 4;</code>
     */
    java.util.List<? extends ru.siksmfp.serialization.harness.model.proto.UserProto.AddressOrBuilder> 
        getAddressesOrBuilderList();
    /**
     * <code>repeated .Address addresses = 4;</code>
     */
    ru.siksmfp.serialization.harness.model.proto.UserProto.AddressOrBuilder getAddressesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      name_ = "";
      signature_ = com.google.protobuf.ByteString.EMPTY;
      addresses_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new User();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {

              signature_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                addresses_ = new java.util.ArrayList<ru.siksmfp.serialization.harness.model.proto.UserProto.Address>();
                mutable_bitField0_ |= 0x00000001;
              }
              addresses_.add(
                  input.readMessage(ru.siksmfp.serialization.harness.model.proto.UserProto.Address.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          addresses_ = java.util.Collections.unmodifiableList(addresses_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.siksmfp.serialization.harness.model.proto.UserProto.internal_static_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.siksmfp.serialization.harness.model.proto.UserProto.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.siksmfp.serialization.harness.model.proto.UserProto.User.class, ru.siksmfp.serialization.harness.model.proto.UserProto.User.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGNATURE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>bytes signature = 3;</code>
     */
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    public static final int ADDRESSES_FIELD_NUMBER = 4;
    private java.util.List<ru.siksmfp.serialization.harness.model.proto.UserProto.Address> addresses_;
    /**
     * <code>repeated .Address addresses = 4;</code>
     */
    public java.util.List<ru.siksmfp.serialization.harness.model.proto.UserProto.Address> getAddressesList() {
      return addresses_;
    }
    /**
     * <code>repeated .Address addresses = 4;</code>
     */
    public java.util.List<? extends ru.siksmfp.serialization.harness.model.proto.UserProto.AddressOrBuilder> 
        getAddressesOrBuilderList() {
      return addresses_;
    }
    /**
     * <code>repeated .Address addresses = 4;</code>
     */
    public int getAddressesCount() {
      return addresses_.size();
    }
    /**
     * <code>repeated .Address addresses = 4;</code>
     */
    public ru.siksmfp.serialization.harness.model.proto.UserProto.Address getAddresses(int index) {
      return addresses_.get(index);
    }
    /**
     * <code>repeated .Address addresses = 4;</code>
     */
    public ru.siksmfp.serialization.harness.model.proto.UserProto.AddressOrBuilder getAddressesOrBuilder(
        int index) {
      return addresses_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!signature_.isEmpty()) {
        output.writeBytes(3, signature_);
      }
      for (int i = 0; i < addresses_.size(); i++) {
        output.writeMessage(4, addresses_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!signature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, signature_);
      }
      for (int i = 0; i < addresses_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, addresses_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.siksmfp.serialization.harness.model.proto.UserProto.User)) {
        return super.equals(obj);
      }
      ru.siksmfp.serialization.harness.model.proto.UserProto.User other = (ru.siksmfp.serialization.harness.model.proto.UserProto.User) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getSignature()
          .equals(other.getSignature())) return false;
      if (!getAddressesList()
          .equals(other.getAddressesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      if (getAddressesCount() > 0) {
        hash = (37 * hash) + ADDRESSES_FIELD_NUMBER;
        hash = (53 * hash) + getAddressesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.siksmfp.serialization.harness.model.proto.UserProto.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.siksmfp.serialization.harness.model.proto.UserProto.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.siksmfp.serialization.harness.model.proto.UserProto.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.siksmfp.serialization.harness.model.proto.UserProto.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.siksmfp.serialization.harness.model.proto.UserProto.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.siksmfp.serialization.harness.model.proto.UserProto.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.siksmfp.serialization.harness.model.proto.UserProto.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.siksmfp.serialization.harness.model.proto.UserProto.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.siksmfp.serialization.harness.model.proto.UserProto.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.siksmfp.serialization.harness.model.proto.UserProto.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.siksmfp.serialization.harness.model.proto.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.siksmfp.serialization.harness.model.proto.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.siksmfp.serialization.harness.model.proto.UserProto.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:User)
        ru.siksmfp.serialization.harness.model.proto.UserProto.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.siksmfp.serialization.harness.model.proto.UserProto.internal_static_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.siksmfp.serialization.harness.model.proto.UserProto.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.siksmfp.serialization.harness.model.proto.UserProto.User.class, ru.siksmfp.serialization.harness.model.proto.UserProto.User.Builder.class);
      }

      // Construct using ru.siksmfp.serialization.harness.model.proto.UserProto.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAddressesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        name_ = "";

        signature_ = com.google.protobuf.ByteString.EMPTY;

        if (addressesBuilder_ == null) {
          addresses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          addressesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.siksmfp.serialization.harness.model.proto.UserProto.internal_static_User_descriptor;
      }

      @java.lang.Override
      public ru.siksmfp.serialization.harness.model.proto.UserProto.User getDefaultInstanceForType() {
        return ru.siksmfp.serialization.harness.model.proto.UserProto.User.getDefaultInstance();
      }

      @java.lang.Override
      public ru.siksmfp.serialization.harness.model.proto.UserProto.User build() {
        ru.siksmfp.serialization.harness.model.proto.UserProto.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.siksmfp.serialization.harness.model.proto.UserProto.User buildPartial() {
        ru.siksmfp.serialization.harness.model.proto.UserProto.User result = new ru.siksmfp.serialization.harness.model.proto.UserProto.User(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.name_ = name_;
        result.signature_ = signature_;
        if (addressesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            addresses_ = java.util.Collections.unmodifiableList(addresses_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.addresses_ = addresses_;
        } else {
          result.addresses_ = addressesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.siksmfp.serialization.harness.model.proto.UserProto.User) {
          return mergeFrom((ru.siksmfp.serialization.harness.model.proto.UserProto.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.siksmfp.serialization.harness.model.proto.UserProto.User other) {
        if (other == ru.siksmfp.serialization.harness.model.proto.UserProto.User.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
          setSignature(other.getSignature());
        }
        if (addressesBuilder_ == null) {
          if (!other.addresses_.isEmpty()) {
            if (addresses_.isEmpty()) {
              addresses_ = other.addresses_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAddressesIsMutable();
              addresses_.addAll(other.addresses_);
            }
            onChanged();
          }
        } else {
          if (!other.addresses_.isEmpty()) {
            if (addressesBuilder_.isEmpty()) {
              addressesBuilder_.dispose();
              addressesBuilder_ = null;
              addresses_ = other.addresses_;
              bitField0_ = (bitField0_ & ~0x00000001);
              addressesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAddressesFieldBuilder() : null;
            } else {
              addressesBuilder_.addAllMessages(other.addresses_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.siksmfp.serialization.harness.model.proto.UserProto.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.siksmfp.serialization.harness.model.proto.UserProto.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes signature = 3;</code>
       */
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>bytes signature = 3;</code>
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes signature = 3;</code>
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }

      private java.util.List<ru.siksmfp.serialization.harness.model.proto.UserProto.Address> addresses_ =
        java.util.Collections.emptyList();
      private void ensureAddressesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          addresses_ = new java.util.ArrayList<ru.siksmfp.serialization.harness.model.proto.UserProto.Address>(addresses_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ru.siksmfp.serialization.harness.model.proto.UserProto.Address, ru.siksmfp.serialization.harness.model.proto.UserProto.Address.Builder, ru.siksmfp.serialization.harness.model.proto.UserProto.AddressOrBuilder> addressesBuilder_;

      /**
       * <code>repeated .Address addresses = 4;</code>
       */
      public java.util.List<ru.siksmfp.serialization.harness.model.proto.UserProto.Address> getAddressesList() {
        if (addressesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(addresses_);
        } else {
          return addressesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Address addresses = 4;</code>
       */
      public int getAddressesCount() {
        if (addressesBuilder_ == null) {
          return addresses_.size();
        } else {
          return addressesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Address addresses = 4;</code>
       */
      public ru.siksmfp.serialization.harness.model.proto.UserProto.Address getAddresses(int index) {
        if (addressesBuilder_ == null) {
          return addresses_.get(index);
        } else {
          return addressesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Address addresses = 4;</code>
       */
      public Builder setAddresses(
          int index, ru.siksmfp.serialization.harness.model.proto.UserProto.Address value) {
        if (addressesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressesIsMutable();
          addresses_.set(index, value);
          onChanged();
        } else {
          addressesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Address addresses = 4;</code>
       */
      public Builder setAddresses(
          int index, ru.siksmfp.serialization.harness.model.proto.UserProto.Address.Builder builderForValue) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          addresses_.set(index, builderForValue.build());
          onChanged();
        } else {
          addressesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Address addresses = 4;</code>
       */
      public Builder addAddresses(ru.siksmfp.serialization.harness.model.proto.UserProto.Address value) {
        if (addressesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressesIsMutable();
          addresses_.add(value);
          onChanged();
        } else {
          addressesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Address addresses = 4;</code>
       */
      public Builder addAddresses(
          int index, ru.siksmfp.serialization.harness.model.proto.UserProto.Address value) {
        if (addressesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressesIsMutable();
          addresses_.add(index, value);
          onChanged();
        } else {
          addressesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Address addresses = 4;</code>
       */
      public Builder addAddresses(
          ru.siksmfp.serialization.harness.model.proto.UserProto.Address.Builder builderForValue) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          addresses_.add(builderForValue.build());
          onChanged();
        } else {
          addressesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Address addresses = 4;</code>
       */
      public Builder addAddresses(
          int index, ru.siksmfp.serialization.harness.model.proto.UserProto.Address.Builder builderForValue) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          addresses_.add(index, builderForValue.build());
          onChanged();
        } else {
          addressesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Address addresses = 4;</code>
       */
      public Builder addAllAddresses(
          java.lang.Iterable<? extends ru.siksmfp.serialization.harness.model.proto.UserProto.Address> values) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, addresses_);
          onChanged();
        } else {
          addressesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Address addresses = 4;</code>
       */
      public Builder clearAddresses() {
        if (addressesBuilder_ == null) {
          addresses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          addressesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Address addresses = 4;</code>
       */
      public Builder removeAddresses(int index) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          addresses_.remove(index);
          onChanged();
        } else {
          addressesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Address addresses = 4;</code>
       */
      public ru.siksmfp.serialization.harness.model.proto.UserProto.Address.Builder getAddressesBuilder(
          int index) {
        return getAddressesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Address addresses = 4;</code>
       */
      public ru.siksmfp.serialization.harness.model.proto.UserProto.AddressOrBuilder getAddressesOrBuilder(
          int index) {
        if (addressesBuilder_ == null) {
          return addresses_.get(index);  } else {
          return addressesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Address addresses = 4;</code>
       */
      public java.util.List<? extends ru.siksmfp.serialization.harness.model.proto.UserProto.AddressOrBuilder> 
           getAddressesOrBuilderList() {
        if (addressesBuilder_ != null) {
          return addressesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(addresses_);
        }
      }
      /**
       * <code>repeated .Address addresses = 4;</code>
       */
      public ru.siksmfp.serialization.harness.model.proto.UserProto.Address.Builder addAddressesBuilder() {
        return getAddressesFieldBuilder().addBuilder(
            ru.siksmfp.serialization.harness.model.proto.UserProto.Address.getDefaultInstance());
      }
      /**
       * <code>repeated .Address addresses = 4;</code>
       */
      public ru.siksmfp.serialization.harness.model.proto.UserProto.Address.Builder addAddressesBuilder(
          int index) {
        return getAddressesFieldBuilder().addBuilder(
            index, ru.siksmfp.serialization.harness.model.proto.UserProto.Address.getDefaultInstance());
      }
      /**
       * <code>repeated .Address addresses = 4;</code>
       */
      public java.util.List<ru.siksmfp.serialization.harness.model.proto.UserProto.Address.Builder> 
           getAddressesBuilderList() {
        return getAddressesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ru.siksmfp.serialization.harness.model.proto.UserProto.Address, ru.siksmfp.serialization.harness.model.proto.UserProto.Address.Builder, ru.siksmfp.serialization.harness.model.proto.UserProto.AddressOrBuilder> 
          getAddressesFieldBuilder() {
        if (addressesBuilder_ == null) {
          addressesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ru.siksmfp.serialization.harness.model.proto.UserProto.Address, ru.siksmfp.serialization.harness.model.proto.UserProto.Address.Builder, ru.siksmfp.serialization.harness.model.proto.UserProto.AddressOrBuilder>(
                  addresses_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          addresses_ = null;
        }
        return addressesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:User)
    }

    // @@protoc_insertion_point(class_scope:User)
    private static final ru.siksmfp.serialization.harness.model.proto.UserProto.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.siksmfp.serialization.harness.model.proto.UserProto.User();
    }

    public static ru.siksmfp.serialization.harness.model.proto.UserProto.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.siksmfp.serialization.harness.model.proto.UserProto.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddressOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Address)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string city = 2;</code>
     */
    java.lang.String getCity();
    /**
     * <code>string city = 2;</code>
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>int32 population = 3;</code>
     */
    int getPopulation();
  }
  /**
   * Protobuf type {@code Address}
   */
  public  static final class Address extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Address)
      AddressOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Address.newBuilder() to construct.
    private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Address() {
      city_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Address();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Address(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              city_ = s;
              break;
            }
            case 24: {

              population_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.siksmfp.serialization.harness.model.proto.UserProto.internal_static_Address_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.siksmfp.serialization.harness.model.proto.UserProto.internal_static_Address_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.siksmfp.serialization.harness.model.proto.UserProto.Address.class, ru.siksmfp.serialization.harness.model.proto.UserProto.Address.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int CITY_FIELD_NUMBER = 2;
    private volatile java.lang.Object city_;
    /**
     * <code>string city = 2;</code>
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <code>string city = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POPULATION_FIELD_NUMBER = 3;
    private int population_;
    /**
     * <code>int32 population = 3;</code>
     */
    public int getPopulation() {
      return population_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getCityBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, city_);
      }
      if (population_ != 0) {
        output.writeInt32(3, population_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getCityBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, city_);
      }
      if (population_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, population_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.siksmfp.serialization.harness.model.proto.UserProto.Address)) {
        return super.equals(obj);
      }
      ru.siksmfp.serialization.harness.model.proto.UserProto.Address other = (ru.siksmfp.serialization.harness.model.proto.UserProto.Address) obj;

      if (getId()
          != other.getId()) return false;
      if (!getCity()
          .equals(other.getCity())) return false;
      if (getPopulation()
          != other.getPopulation()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + getCity().hashCode();
      hash = (37 * hash) + POPULATION_FIELD_NUMBER;
      hash = (53 * hash) + getPopulation();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.siksmfp.serialization.harness.model.proto.UserProto.Address parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.siksmfp.serialization.harness.model.proto.UserProto.Address parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.siksmfp.serialization.harness.model.proto.UserProto.Address parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.siksmfp.serialization.harness.model.proto.UserProto.Address parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.siksmfp.serialization.harness.model.proto.UserProto.Address parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.siksmfp.serialization.harness.model.proto.UserProto.Address parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.siksmfp.serialization.harness.model.proto.UserProto.Address parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.siksmfp.serialization.harness.model.proto.UserProto.Address parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.siksmfp.serialization.harness.model.proto.UserProto.Address parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.siksmfp.serialization.harness.model.proto.UserProto.Address parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.siksmfp.serialization.harness.model.proto.UserProto.Address parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.siksmfp.serialization.harness.model.proto.UserProto.Address parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.siksmfp.serialization.harness.model.proto.UserProto.Address prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Address}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Address)
        ru.siksmfp.serialization.harness.model.proto.UserProto.AddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.siksmfp.serialization.harness.model.proto.UserProto.internal_static_Address_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.siksmfp.serialization.harness.model.proto.UserProto.internal_static_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.siksmfp.serialization.harness.model.proto.UserProto.Address.class, ru.siksmfp.serialization.harness.model.proto.UserProto.Address.Builder.class);
      }

      // Construct using ru.siksmfp.serialization.harness.model.proto.UserProto.Address.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        city_ = "";

        population_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.siksmfp.serialization.harness.model.proto.UserProto.internal_static_Address_descriptor;
      }

      @java.lang.Override
      public ru.siksmfp.serialization.harness.model.proto.UserProto.Address getDefaultInstanceForType() {
        return ru.siksmfp.serialization.harness.model.proto.UserProto.Address.getDefaultInstance();
      }

      @java.lang.Override
      public ru.siksmfp.serialization.harness.model.proto.UserProto.Address build() {
        ru.siksmfp.serialization.harness.model.proto.UserProto.Address result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.siksmfp.serialization.harness.model.proto.UserProto.Address buildPartial() {
        ru.siksmfp.serialization.harness.model.proto.UserProto.Address result = new ru.siksmfp.serialization.harness.model.proto.UserProto.Address(this);
        result.id_ = id_;
        result.city_ = city_;
        result.population_ = population_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.siksmfp.serialization.harness.model.proto.UserProto.Address) {
          return mergeFrom((ru.siksmfp.serialization.harness.model.proto.UserProto.Address)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.siksmfp.serialization.harness.model.proto.UserProto.Address other) {
        if (other == ru.siksmfp.serialization.harness.model.proto.UserProto.Address.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          onChanged();
        }
        if (other.getPopulation() != 0) {
          setPopulation(other.getPopulation());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.siksmfp.serialization.harness.model.proto.UserProto.Address parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.siksmfp.serialization.harness.model.proto.UserProto.Address) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <code>string city = 2;</code>
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string city = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string city = 2;</code>
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        city_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string city = 2;</code>
       */
      public Builder clearCity() {
        
        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      /**
       * <code>string city = 2;</code>
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        city_ = value;
        onChanged();
        return this;
      }

      private int population_ ;
      /**
       * <code>int32 population = 3;</code>
       */
      public int getPopulation() {
        return population_;
      }
      /**
       * <code>int32 population = 3;</code>
       */
      public Builder setPopulation(int value) {
        
        population_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 population = 3;</code>
       */
      public Builder clearPopulation() {
        
        population_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Address)
    }

    // @@protoc_insertion_point(class_scope:Address)
    private static final ru.siksmfp.serialization.harness.model.proto.UserProto.Address DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.siksmfp.serialization.harness.model.proto.UserProto.Address();
    }

    public static ru.siksmfp.serialization.harness.model.proto.UserProto.Address getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Address>
        PARSER = new com.google.protobuf.AbstractParser<Address>() {
      @java.lang.Override
      public Address parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Address(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Address> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Address> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.siksmfp.serialization.harness.model.proto.UserProto.Address getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Address_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\"P\n\004User\022\n\n\002id\030\001 \001(\003\022\014\n\004name" +
      "\030\002 \001(\t\022\021\n\tsignature\030\003 \001(\014\022\033\n\taddresses\030\004" +
      " \003(\0132\010.Address\"7\n\007Address\022\n\n\002id\030\001 \001(\003\022\014\n" +
      "\004city\030\002 \001(\t\022\022\n\npopulation\030\003 \001(\005B9\n,ru.si" +
      "ksmfp.serialization.harness.model.protoB" +
      "\tUserProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Id", "Name", "Signature", "Addresses", });
    internal_static_Address_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Address_descriptor,
        new java.lang.String[] { "Id", "City", "Population", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
